Models/Question.cs
using QuestionApp.ViewModels;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace QuestionApp.Models
{
    public class Question
    {
        public int Id { get; set; }

        [Required]
        [Display(Name = "Başlık")]
        public string Title { get; set; }

        [Required]
        [Display(Name = "Açıklama")]
        public string Description { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [FutureDate(ErrorMessage = "Geçerli bir tarih giriniz.")]
        [Display(Name = "Son Geçerlilik Tarihi")]
        public DateTime Deadline { get; set; }

        public DateTime CreateDate { get; set; }

        [Required]
        [Display(Name = "Gereken Onay Sayısı")]
        [Range(0, int.MaxValue, ErrorMessage = "Onay sayısı negatif olamaz.")]
        public int NumberofAffirmativesRequired { get; set; }
        public IList<ResponseModel> Responses { get; set; }
        public bool IsActive { get; set; }

        public Question()
        {
            this.CreateDate = DateTime.Now;
            this.IsActive = true;
        }
    }
}

Controllers/QuestionsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using QuestionApp.Models;
using QuestionApp.Repositories;
using Syncfusion.DocIO;
using Syncfusion.DocIO.DLS;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace QuestionApp.Controllers
{
    public class QuestionsController : Controller
    {
        private readonly IQuestionRepository questionRepository;

        public QuestionsController(IQuestionRepository questionRepository)
        {
            this.questionRepository = questionRepository;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles ="Admin")]
        [HttpPost]
        public IActionResult Create(Question model)
        {
            if (ModelState.IsValid)
            {
                questionRepository.AddQuestion(model);
                return RedirectToAction("List", "Questions");
            }
            return View(model);
        }

        public IActionResult List()
        {
            var questions = questionRepository.GetQuestionsWithResponses();
            return View(questions);
        }

       
        [HttpPost]

        public IActionResult DeadlineControl(int questionId)
        {
            var result = questionRepository.IsQuestionValid(questionId);
            return Json(result);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult DownloadDocument(int questionId)
        {
            var questionTitle = questionRepository.GetQuestion(questionId).Title;
            WordDocument document = GenerateDocument(questionId);
            //Saves the Word document to  MemoryStream
            MemoryStream stream = new MemoryStream();
            document.Save(stream, FormatType.Docx);
            stream.Position = 0;

            //Download Word document in the browser
            return File(stream, "application/msword", $"{questionTitle}.docx");
        }


        [Authorize(Roles = "Admin")]
        public IActionResult QuestionDetails(int questionId)
        {
            var question = questionRepository.GetQuestion(questionId);
            return View(question);
        }


        [Authorize(Roles ="Admin")]
        public IActionResult Cancel(int questionId)
        {
            questionRepository.CancelQuestion(questionId);
            return Redirect("/Questions/List");
        }

        private WordDocument GenerateDocument(int questionId)
        {
            var question = questionRepository.GetQuestion(questionId);
            WordDocument document = new WordDocument();
            //Adding a new section to the document.
            WSection section = document.AddSection() as WSection;
            //Set Margin of the section
            section.PageSetup.Margins.All = 72;
            //Set page size of the section
            section.PageSetup.PageSize = new Syncfusion.Drawing.SizeF(612, 792);
            IWParagraph paragraph = section.HeadersFooters.Header.AddParagraph();
            paragraph.ApplyStyle("Normal");
            paragraph.ParagraphFormat.HorizontalAlignment = HorizontalAlignment.Left;
            WTextRange textRange = paragraph.AppendText($"'{question.Title}' başlıklı soru yanıtları") as WTextRange;
            textRange.CharacterFormat.FontSize = 12f;
            textRange.CharacterFormat.FontName = "Calibri";
            textRange.CharacterFormat.TextColor = Syncfusion.Drawing.Color.Black;

            var list = question.Responses.OrderByDescending(r => r.ResponseDate);

            foreach (var response in list)
            {
                paragraph = section.AddParagraph();
                paragraph.BreakCharacterFormat.FontSize = 12f;
                textRange = paragraph.AppendText(response.Username + ": " + (response.Response == true ? "Evet" : "Hayır")) as WTextRange;
                textRange = paragraph.AppendText($"  ({response.ResponseDate})") as WTextRange;
                paragraph = section.AddParagraph();
                textRange = paragraph.AppendText("Not: " + (response.Note == null ? "-" : response.Note)) as WTextRange;
                paragraph = section.AddParagraph();
                textRange = paragraph.AppendText("----------------------") as WTextRange;
                textRange.CharacterFormat.FontSize = 12f;
            }
            section.AddParagraph();

            return document;
        }
    }
}

Controllers/ResponsesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using QuestionApp.Extensions;
using QuestionApp.Models;
using QuestionApp.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Mail;
using System.Threading.Tasks;

namespace QuestionApp.Controllers
{
    public class ResponsesController : Controller
    {
        private readonly IQuestionRepository questionRepository;
        private readonly IResponseRepository responseRepository;
        private readonly IEmailService emailService;

        public ResponsesController(IQuestionRepository questionRepository, IResponseRepository responseRepository, IEmailService emailService)
        {
            this.questionRepository = questionRepository;
            this.responseRepository = responseRepository;
            this.emailService = emailService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [Authorize]
        public IActionResult Create(int questionId)
        {
            ResponseModel response = new ResponseModel
            {
                Question = questionRepository.GetQuestion(questionId),
                Username = User.GetUsername(),
                ResponseDate = DateTime.Now


            };
            return View(response);
        }

        [Authorize]
        [HttpPost]
        public IActionResult Create(ResponseModel model)
        {
            ResponseModel res = new ResponseModel
            {
                QuestionId = model.QuestionId,
                Username = model.Username,
                Response = model.Response,
                ResponseDate = model.ResponseDate,
                Note = model.Note
            };

            if (ModelState.IsValid)
            {
                responseRepository.AddResponse(res);
                if (res.Response)
                {
                    string questionTitle = questionRepository.GetQuestion(res.QuestionId).Title;
                    emailService.SendEmailForAffirmative(res.Username, questionTitle, res.Note);
                    if (IsRequiredProvided(res.QuestionId)) emailService.SendEmailForReachedNumberOfAffirmatives(res.Question.Title);
                }
            }
            return Redirect("/Questions/List");
        }

       


        private bool IsRequiredProvided(int questionId)
        {
            return questionRepository.IsQuestionApproved(questionId);
        }
       

        public IActionResult Affirmatives(int questionId)
        {
            var responseList = responseRepository.GetQuestionsAffirmativeResponses(questionId);
            return View(responseList);
        }
        public IActionResult Negatives(int questionId)
        {
            var responseList = responseRepository.GetQuestionsRejectedResponses(questionId);
            return View(responseList);
        }

        [HttpPost]
        public IActionResult ResponseControl(int questionId)
        {
            string username = User.GetUsername();
            var result = responseRepository.HasUserResponded(username, questionId);
            return Json(result);
        }


        [HttpPost]
        public IActionResult MyResponse(int questionId)
        {
            string username = User.GetUsername();
            var result = responseRepository.GetUserResponse(username, questionId);
            if (result)
            {
                return Json("Evet");
            }
            return Json("Hayır");
        }
    }
}

Views/Questions/Create.cshtml
@model Question

@{
    ViewData["Title"] = "Create";
}

<h3>Soru Oluştur</h3>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>

            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />

            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control" rows="4" cols="50"></textarea>

            </div>
            <div class="form-group" style="width:155px;">
                <label asp-for="Deadline" class="control-label"></label>
                <input asp-for="Deadline" class="form-control" />

            </div>
            <div class="form-group" style="width:100px;">
                <label asp-for="NumberofAffirmativesRequired" class="control-label"></label>
                <input asp-for="NumberofAffirmativesRequired" class="form-control" />

            </div>

            <div class="form-group">
                <input type="submit" value="Kaydet" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

Views/Questions/List.cshtml
@model IEnumerable<Question>

@{
    ViewData["Title"] = "List";
}

<h3>Sorular</h3>

@if (Model.Count() == 0)
{
    <div class="alert alert-warning">Aktif soru bulunmamaktadır.</div>
}

@foreach (var question in Model)
{


    <div class="card">
        @if (User.IsInRole("Admin"))
        {
            <h5 class="card-header">
                <a asp-action="QuestionDetails" asp-controller="Questions" asp-route-questionId="@question.Id">Soru</a>
            </h5>
        }
        else
        {
            <h5 class="card-header">Soru</h5>
        }

        <div class="card-body">
            <h5 class="card-title">@question.Title</h5>
            <p class="card-text">@question.Description</p>
            <p class="card-text">

                Evet: @question.Responses.Where(s => s.Response).Count()


                Hayır: @question.Responses.Where(s => s.Response == false).Count()


            </p>
            @if (!User.Identity.IsAuthenticated || User.IsInRole("Member"))
            {
                <a asp-action="Create" asp-controller="Responses" asp-route-questionId="@question.Id" asp-route-returnUrl="/Responses/Create/" class="btn btn-primary">Yanıtla!</a>
            }

        </div>
    </div>
    <br />
}

Views/Questions/QuestionDetails.cshtml
@model Question
@{
    ViewData["Title"] = "QuestionDetails";
    var numOfAffirmativesRequired = Model.NumberofAffirmativesRequired - Model.Responses.Where(r => r.Response).Count();
    int numOfAffirmatives = Model.Responses.Where(r => r.Response == true).Count();
    int numOfNegatives = Model.Responses.Where(r => r.Response == false).Count();
}
<div class="row">
    <div class="col-9" style="margin-top:20px;">
        <div class="container">
            <h3>@Model.Title</h3>
            <br />
            <p>@Model.Description</p>
            <p class="affirmatives" numOfAffirmatives="@numOfAffirmatives">
                <a asp-action="Affirmatives" asp-controller="Responses" asp-route-questionId="@Model.Id">
                    Evet: @numOfAffirmatives
                </a>
            </p>
            <p class="negatives" numOfNegatives="@numOfNegatives">
                <a asp-action="Negatives" asp-controller="Responses" asp-route-questionId="@Model.Id">
                    Hayır: @numOfNegatives
                </a>
            </p>
            <p>Kapanma tarihi: @Model.Deadline.ToShortDateString()</p>
            <p>Kalan gerekli onay sayısı: @(numOfAffirmativesRequired >= 0? numOfAffirmativesRequired : 0)</p>
            <hr />
            <a asp-action="DownloadDocument" asp-controller="Questions" asp-route-questionId="@Model.Id">Word dosyası oluştur</a>
            <hr />
            <a href="#" class="removeQuestion" questionId="@Model.Id">
                Soruyu kaldır
            </a>

        </div>
    </div>
    <div class="col-3">
        <div id="piechart"></div>

    </div>
</div>





@section Scripts{
    <script>

        var numOfAffirmatives = Number($('.affirmatives').attr('numOfAffirmatives'));
        var numOfNegatives = Number($('.negatives').attr('numOfNegatives'));

        google.charts.load('current', { 'packages': ['corechart'] });
        google.charts.setOnLoadCallback(drawChart);

        // Draws the chart and set the chart values
        function drawChart() {
            var data = google.visualization.arrayToDataTable([
                ['Response', 'Number'],
                ['Evet', numOfAffirmatives],
                ['Hayır', numOfNegatives]

            ]);


            var options = { 'title': 'Cevaplar', 'width': 450, 'height': 300 };
            var chart = new google.visualization.PieChart(document.getElementById('piechart'));
            chart.draw(data, options);
        }

        $(document).ready(function () {
            $('.removeQuestion').click(function (e) {
                var questionId = $(this).attr('questionId');
                e.preventDefault();
                if (confirm("Soruyu silmek istediğinize emin misiniz?")) {
                    $.post("/Questions/Cancel", { questionId: questionId })
                        .done(function () {
                            location = "/Questions/List";
                        })
                }
            })


        })

    </script>

}